sudo: required
dist: bionic
language: csharp
solution: SharpXMPP.sln
dotnet: 2.2
mono: 4.2.3
install:
  - dotnet restore
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
before_script:
  - export FrameworkPathOverride=/usr/lib/mono/4.5/
script:
  - dotnet test ./SharpXMPP.NUnit/SharpXMPP.NUnit.csproj -f netcoreapp1.1
  - dotnet build SharpXMPP.NUnit -f net451
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./SharpXMPP.NUnit/bin/Debug/net451/SharpXMPP.NUnit.dll
