sudo: required
dist: trusty
language: csharp
solution: SharpXMPP.sln
matrix:
  include:
    - dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
    - mono: latest
install:
  - if [ -z "$DOTNETCORE" ]; then nuget restore SharpXMPP.sln; fi
  - if [ -z "$DOTNETCORE" ]; then nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner; fi
  - if [[ "$DOTNETCORE" == 1 ]]; then dotnet restore SharpXMPP.NUnit; fi
script:
  - if [ -z "$DOTNETCORE" ]; then xbuild /p:Configuration=Release SharpXMPP.NUnit/SharpXMPP.NUnit.csproj; fi
  - if [ -z "$DOTNETCORE" ]; then mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./SharpXMPP.NUnit/bin/Release/SharpXMPP.NUnit.dll; fi
  - if [[ "$DOTNETCORE" == 1 ]]; then dotnet test SharpXMPP.NUnit; fi
