sudo: required
dist: trusty
language: csharp
solution: SharpXMPP.sln
matrix:
  include:
    - dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
    - mono: latest
install:
  - nuget restore SharpXMPP.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SharpXMPP.NUnit/SharpXMPP.NUnit.csproj
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./SharpXMPP.NUnit/bin/Release/SharpXMPP.NUnit.dll
