before_build:
    - dotnet restore
    - nuget install SharpXMPP.WPF/packages.config -SolutionDirectory .
    - dotnet build SharpXMPP.Shared -f netstandard1.6
build:
    project: SharpXMPP.sln
test:
    assemblies: SharpXMPP.NUnit/bin/Debug/net451/win7-x64/SharpXMPP.NUnit.dll
