image: Visual Studio 2017
before_build:
    - dotnet restore
    - nuget restore
    - nuget install SharpXMPP.WPF/packages.config -SolutionDirectory .
    - dotnet build SharpXMPP.Shared -f netstandard1.6
build:
    project: SharpXMPP.sln
test:
    assemblies:
        only:
            - SharpXMPP.NUnit/bin/Debug/**/SharpXMPP.NUnit.dll
