name: .NET

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    - name: Build console app
      if: matrix.os == 'ubuntu-latest'
      run: dotnet build SharpXMPP.Console
    - name: Build WPF app
      if: matrix.os == 'windows-latest'
      run: |
        nuget restore SharpXMPP.WPF/SharpXMPP.WPF.csproj
        dotnet build SharpXMPP.WPF
    - name: Build Xamarin apps
      if: matrix.os == 'macos-latest'
      run: |
        nuget restore SharpXMPP.sln
        msbuild SharpXMPP.Xamarin/SharpXMPP.Client.iOS/SharpXMPP.Client.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
        msbuild SharpXMPP.Xamarin/SharpXMPP.Client.Droid/SharpXMPP.Client.Droid.csproj /p:Configuration=Debug /t:PackageForAndroid
    - name: Run tests
      run: dotnet test SharpXMPP.NUnit -f net5.0
