name: .NET

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: nuget restore SharpXMPP.sln
    - name: Build console app
      if: matrix.os == 'ubuntu-latest'
      run: dotnet build SharpXMPP.Console
    - name: Build WPF app
      if: matrix.os == 'windows-latest'
      run: dotnet build SharpXMPP.WPF
    - name: Build Xamarin apps
      if: matrix.os == 'macos-latest'
      run: |
        dotnet build SharpXMPP.Xamarin/SharpXMPP.Client.iOS
        dotnet build SharpXMPP.Xamarin/SharpXMPP.Client.Android
    - name: Run tests
      run: dotnet test SharpXMPP.NUnit --no-restore
