name: .NET

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - uses: weslleymurdock/setup-maui-action@v1.1
      if: matrix.os == 'macos-latest'
      with:
        dotnet-version: 9.0.x
    - name: Add msbuild to PATH
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v2
    - name: Restore workloads
      run: dotnet workload restore
    - name: Build console app
      run: dotnet build SharpXMPP.Console
    - name: Build WPF app
      if: matrix.os == 'windows-latest'
      run: |
        nuget restore SharpXMPP.sln
        msbuild SharpXMPP.WPF/SharpXMPP.WPF.csproj /p:Configuration=Debug /t:Rebuild
    - name: Build mobile app
      if: matrix.os == 'macos-latest'
      run: |
        sudo xcode-select -switch /Applications/Xcode_26.0.1.app/Contents/Developer
        dotnet build SharpXMPP.Mobile --configuration Release --framework net9.0-maccatalyst
    - name: Run .NET 9.0 tests
      run: dotnet test SharpXMPP.NUnit -f net9.0
    - name: Configure Mono
      if: matrix.os == 'ubuntu-22.04'
      run: |
        echo "mono_path=/usr/lib/mono/4.5/" >> $GITHUB_ENV
    - name: Build tests with .NET 4.8/Mono
      if: matrix.os != 'macos-latest'
      run: dotnet build SharpXMPP.NUnit --no-restore --configuration Release -f net48
      env:
        FrameworkPathOverride: ${{ env.mono_path }}
    - name: Run tests with .NET 4.8/Mono
      if: matrix.os != 'macos-latest'
      run: dotnet test SharpXMPP.NUnit --no-restore --no-build --configuration Release -f net48
      env:
        FrameworkPathOverride: ${{ env.mono_path }}

    - name: Build the SharpXMPP.Shared package
      run: cd SharpXMPP.Shared && dotnet pack --configuration Release
      if: matrix.os == 'ubuntu-22.04'
    - name: Build the SharpXMPP.WebSocket package
      run: cd SharpXMPP.WebSocket && dotnet pack --configuration Release
      if: matrix.os == 'ubuntu-22.04'
    - name: Upload the NuGet packages
      uses: actions/upload-artifact@v6
      if: matrix.os == 'ubuntu-22.04'
      with:
        name: nuget
        path: |
          SharpXMPP.Shared/bin/Release/*.nupkg
          SharpXMPP.WebSocket/bin/Release/*.nupkg
