name: .NET

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Run .NET Core tests
      run: dotnet test SharpXMPP.NUnit --no-restore --configuration Release -f netcoreapp3.1
    - name: Configure Mono
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "/usr/lib/mono/4.5/" >> $MONO_PATH
    - name: Build tests with .NET 4.8/Mono
      if: matrix.os != 'macos-latest'
      run: dotnet build SharpXMPP.NUnit --no-restore --configuration Release -f net48
      env:
        FrameworkPathOverride: ${{ env.MONO_PATH }}
    - name: Run tests with .NET 4.8/Mono
      if: matrix.os != 'macos-latest'
      run: dotnet test SharpXMPP.NUnit --no-restore --no-build --configuration Release -f net48
      env:
        FrameworkPathOverride: ${{ env.MONO_PATH }}
