name: .NET

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: nuget restore SharpXMPP.sln
    - name: Build console app
      run: msbuild SharpXMPP.Console/SharpXMPP.Console.csproj /p:Configuration=Debug /t:Rebuild
    - name: Build WPF apps
      if: matrix.os == 'windows-latest'
      run: msbuild SharpXMPP.WPF/SharpXMPP.WPF.csproj /p:Configuration=Debug /t:Rebuild
    - name: Build Xamarin apps
      if: matrix.os == 'macos-latest'
      run: |
        msbuild SharpXMPP.Xamarin/SharpXMPP.Client.iOS/SharpXMPP.Client.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
        msbuild SharpXMPP.Xamarin/SharpXMPP.Client.Android/SharpXMPP.Client.Android.csproj /p:Configuration=Debug /t:PackageForAndroid
    - name: Run .NET 5.0 tests
      run: dotnet test SharpXMPP.NUnit --no-restore --configuration Release -f net5.0
