name: .NET Core

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Run .NET Core tests
      run: dotnet test SharpXMPP.NUnit --no-restore --configuration Release -f netcoreapp3.1
    - name: Configure Mono
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "::set-env name=mono_path::/usr/lib/mono/4.5/"
    - name: Build tests with .NET 4.8/Mono
      if: matrix.os != 'macos-latest'
      run: dotnet build SharpXMPP.NUnit --no-restore --configuration Release -f net48
      env:
        FrameworkPathOverride: ${{ env.mono_path }}
    - name: Run tests with .NET 4.8/Mono
      if: matrix.os != 'macos-latest'
      run: dotnet test SharpXMPP.NUnit --no-restore --no-build --configuration Release -f net48
      env:
        FrameworkPathOverride: ${{ env.mono_path }}
